mod-name: NearFutureSolar
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - NearFutureSolar
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.4
    location: s3
  B9PartSwitch:
    version: 2.18.0
    location: s3
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 559  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 220672  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
